### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lploc94**
Add Vietnamese version for Commit-messages-guide

### CODE REVIEW

**Comment by RomuloOliveira** [comment]
Your fork is behind master branch, could you please [sync it up](https://help.github.com/en/articles/syncing-a-fork)?

**Comment by lploc94** [comment]
Hi I have synced it up

**Review by RomuloOliveira — APPROVED** [review]
Thank you, @lploc94

**Comment by lploc94** [comment]
If you have other guide that you want to translate to Vietnamese, feel free to email me: lploc94@gmail.com.

**Pull request merged**
