### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by OnePieceJoker**

### CODE REVIEW

**Comment by OnePieceJoker** [comment]
在翻译完提交之后才发现原来有人已经翻译了中文版本  #17 ，

**Comment by junxy** [comment]
> 在翻译完提交之后才发现原来有人已经翻译了中文版本 #17 ，

看到这个项目的第一想法是，看有没有中文版，没有？可以翻译。嗯，先看看PR中有没有在翻译的。果然有… 😆

**Comment by RomuloOliveira** [comment]
> 在翻译完提交之后才发现原来有人已经翻译了中文版本 #17 ，

Hi, @OnePieceJoker, do you have a suggestion about what we can do about it? Since #17 is not yet merged, I would suggest you to comment there and suggest changes/sentences that you used in this PR, when applied. I'm suggesting this because other people already reviewed that PR.

@seriouszyx @geminiyellow I also appreciate if you could take a look and have any suggestions on resolving this.

**Comment by OnePieceJoker** [comment]
@RomuloOliveira You are right, I will go to #17 to submit my comment.Thanks

**Comment by geminiyellow** [comment]
@RomuloOliveira yep, the best solution is review #17 .

#17 need more reviewer, right?

>  Should I wait for some additional reviews before merging it?

so, @OnePieceJoker 实在抱歉，这个 PR 可以考虑并关掉它，然后在 #17 上进行修改。

粗略的看了一下你的翻译，确实比 #17 顺畅。但是没办法，要么就等 #17 合并之后再做提交，
这样你的提交历史就能出现在 master 上了。:wink:

**Comment by OnePieceJoker** [comment]
@geminiyellow 我觉得在 #17 上提出更多的建议好一点，还是把这个PR关掉了

**Pull request closed without merging**
