### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by Enrico204**
Add the Italian translation in a separate file (as standard) and links
in other translation files (cross-reference).

### CODE REVIEW

**Review by RomuloOliveira — APPROVED** [review]
@Enrico204 thanks for your contribution, I really appreciate it! (I took the liberty of resolving some conflicts that appeared after the merge of #14)

**Comment by RomuloOliveira** [comment]
Sorry, @Enrico204, I screwed up during rebase, I'll fix it in a minute.

**Comment by RomuloOliveira** [comment]
I wasn't able to reopen the PR appropriately, but your contribution [was safely merged and is available in the master branch](https://github.com/RomuloOliveira/commit-messages-guide/blob/master/README_it-IT.md). Sorry for the mess.

**Comment by Enrico204** [comment]
Thanks :-)

**Pull request closed without merging**
